# Generated by Django 4.0.1 on 2022-01-18 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('identifier', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('maturity_rating', models.PositiveSmallIntegerField(choices=[(1, 'L'), (2, '10'), (3, '12'), (4, '14'), (5, '16'), (6, '18')], help_text='Only show title rated with', verbose_name='maturity rating')),
                ('kid_profile', models.BooleanField(blank=True, default=False, help_text='Display the Netflix Kids experience with titles just for kids', verbose_name='kids profile')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
