# Generated by Django 4.0.1 on 2022-01-18 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_maturity_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maturity_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'L'), (2, '10'), (3, '12'), (4, '14'), (5, '16'), (6, '18')], default=1, help_text='Only show title rated with', verbose_name='maturity rating'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
